---
- hosts: localhost

  tasks:
    - name: Install Grafana
      ansible.builtin.package:
        name: grafana
    - name: Install Fish
      ansible.builtin.package:
        name: fish
    - name: Install JQ
      ansible.builtin.package:
        name: jq
    - name: Install AWS CLI
      ansible.builtin.package:
        name: awscli
    - name: Install Terraform
      ansible.builtin.package:
        name: terraform
    - name: Install Vault
      ansible.builtin.package:
        name: vault
    - name: Install TFLint
      ansible.builtin.package:
        name: tflint
    - name: Install Checkov
      ansible.builtin.package:
        name: checkov
    - name: Install Redis
      ansible.builtin.package:
        name: redis
    - name: Install NVM
      ansible.builtin.command: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash'
    # 
    # Below are resource intensive or unreliable installs
    # 
    - name: Install bind suite including dig
      ansible.builtin.package:
        name: bind
    - name: Install openjdk
      ansible.builtin.package:
        name: openjdk
    - name: Install Maven
      ansible.builtin.package:
        name: maven
    - name: Install Groovy
      ansible.builtin.package:
        name: groovy
    # Cask install a bit less reliable
    # - name: Install Sentinel
    #   ansible.builtin.package:
    #     name: sentinel

