---
- hosts: localhost
  vars: 
    rc_file: '~/.zshrc'
  tasks:
    - name: Install Grafana
      ansible.builtin.package:
        name: grafana
    - name: Install K8s CLI
      ansible.builtin.package:
        name: kubectl
    - name: Install Fish
      ansible.builtin.package:
        name: fish
    - name: Install JQ
      ansible.builtin.package:
        name: jq
    - name: Install AWS CLI
      ansible.builtin.package:
        name: awscli
    - name: Install Terraform
      ansible.builtin.package:
        name: terraform
    - name: Install Vault
      ansible.builtin.package:
        name: vault
    - name: Install TFLint
      ansible.builtin.package:
        name: tflint
    - name: Install Checkov
      ansible.builtin.package:
        name: checkov
    - name: Install Redis
      ansible.builtin.package:
        name: redis 
    # TODO Fix NVM install
    # - name: Install NVM
    #   ansible.builtin.command: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash'
    # 
    # Below are resource intensive or unreliable installs
    # 
    - name: Install bind suite including dig
      ansible.builtin.package:
        name: bind
    - name: Install openjdk
      ansible.builtin.package:
        name: openjdk
    - name: Install Maven
      ansible.builtin.package:
        name: maven
    - name: Install Groovy
      ansible.builtin.package:
        name: groovy
    - 
      name: Ensure JAVA_HOME set in desired shell RC
      ansible.builtin.lineinfile:
        path: '{{ rc_file }}'
        insertafter: 'EOF'
        line: 'export JAVA_HOME=/opt/homebrew/opt/java/'
    - 
      name: Ensure GROOVY_HOME set in desired shell RC
      ansible.builtin.lineinfile:
        path: '{{ rc_file }}'
        insertafter: 'EOF'
        line: 'export GROOVY_HOME=/opt/homebrew/opt/groovy/libexec'
    - 
      name: Ensure we have a comment in last line of edited files
      ansible.builtin.lineinfile:
        path: '{{ rc_file }}'
        insertafter: 'EOF'
        line: '# AUTO EDITED BY ANSIBLE'    # Cask install a bit less reliable
    # - name: Install Sentinel
    #   ansible.builtin.package:
    #     name: sentinel

